FROM golang:1.23-alpine
WORKDIR /app

COPY backend/go.mod .
COPY backend/go.sum .
COPY backend/*air.toml .

RUN go mod download

ENV CGO_ENABLED = 0

COPY ./backend .

RUN go install github.com/cosmtrek/air@latest

CMD ["air"]

